language: ruby
sudo: false
cache: bundler
services:
  - redis-server
before_install:
  - gem install bundler
  - gem update bundler
rvm:
  - 2.2.2
  - 2.3.5
  - 2.4.2
  - ruby-head
  - jruby-9.1.14.0
matrix:
  allow_failures:
    - rvm: ruby-head
